//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fields_Of_InJustice.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fields_Of_InJustice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_e0000 {
            get {
                object obj = ResourceManager.GetObject("2walking e0000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_e0001 {
            get {
                object obj = ResourceManager.GetObject("2walking e0001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_e0002 {
            get {
                object obj = ResourceManager.GetObject("2walking e0002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_e0003 {
            get {
                object obj = ResourceManager.GetObject("2walking e0003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_e0004 {
            get {
                object obj = ResourceManager.GetObject("2walking e0004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_e0005 {
            get {
                object obj = ResourceManager.GetObject("2walking e0005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_e0006 {
            get {
                object obj = ResourceManager.GetObject("2walking e0006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_e0007 {
            get {
                object obj = ResourceManager.GetObject("2walking e0007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_n0000 {
            get {
                object obj = ResourceManager.GetObject("2walking n0000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_n0001 {
            get {
                object obj = ResourceManager.GetObject("2walking n0001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_n0002 {
            get {
                object obj = ResourceManager.GetObject("2walking n0002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_n0003 {
            get {
                object obj = ResourceManager.GetObject("2walking n0003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_n0004 {
            get {
                object obj = ResourceManager.GetObject("2walking n0004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_n0005 {
            get {
                object obj = ResourceManager.GetObject("2walking n0005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_n0006 {
            get {
                object obj = ResourceManager.GetObject("2walking n0006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_n0007 {
            get {
                object obj = ResourceManager.GetObject("2walking n0007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_s0000 {
            get {
                object obj = ResourceManager.GetObject("2walking s0000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_s0001 {
            get {
                object obj = ResourceManager.GetObject("2walking s0001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_s0002 {
            get {
                object obj = ResourceManager.GetObject("2walking s0002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_s0003 {
            get {
                object obj = ResourceManager.GetObject("2walking s0003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_s0004 {
            get {
                object obj = ResourceManager.GetObject("2walking s0004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_s0005 {
            get {
                object obj = ResourceManager.GetObject("2walking s0005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_s0006 {
            get {
                object obj = ResourceManager.GetObject("2walking s0006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_s0007 {
            get {
                object obj = ResourceManager.GetObject("2walking s0007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_w0000 {
            get {
                object obj = ResourceManager.GetObject("2walking w0000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_w0001 {
            get {
                object obj = ResourceManager.GetObject("2walking w0001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_w0002 {
            get {
                object obj = ResourceManager.GetObject("2walking w0002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_w0003 {
            get {
                object obj = ResourceManager.GetObject("2walking w0003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_w0004 {
            get {
                object obj = ResourceManager.GetObject("2walking w0004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_w0005 {
            get {
                object obj = ResourceManager.GetObject("2walking w0005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_w0006 {
            get {
                object obj = ResourceManager.GetObject("2walking w0006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2walking_w0007 {
            get {
                object obj = ResourceManager.GetObject("2walking w0007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blue_flamewallflame_appear_0000 {
            get {
                object obj = ResourceManager.GetObject("blue flamewallflame appear 0000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bomb {
            get {
                object obj = ResourceManager.GetObject("Bomb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Explosion {
            get {
                object obj = ResourceManager.GetObject("Explosion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap House_One {
            get {
                object obj = ResourceManager.GetObject("House One", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap House_Two {
            get {
                object obj = ResourceManager.GetObject("House Two", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MainBackground {
            get {
                object obj = ResourceManager.GetObject("MainBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap player1Controls {
            get {
                object obj = ResourceManager.GetObject("player1Controls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap player2Controls {
            get {
                object obj = ResourceManager.GetObject("player2Controls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap red_flamewallflame_appear_0000 {
            get {
                object obj = ResourceManager.GetObject("red flamewallflame appear 0000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rock {
            get {
                object obj = ResourceManager.GetObject("rock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Speed {
            get {
                object obj = ResourceManager.GetObject("Speed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Splash_Screen_Pic {
            get {
                object obj = ResourceManager.GetObject("Splash Screen Pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Time_Freeze {
            get {
                object obj = ResourceManager.GetObject("Time Freeze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tree {
            get {
                object obj = ResourceManager.GetObject("tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_e0000 {
            get {
                object obj = ResourceManager.GetObject("walking e0000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_e0001 {
            get {
                object obj = ResourceManager.GetObject("walking e0001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_e0002 {
            get {
                object obj = ResourceManager.GetObject("walking e0002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_e0003 {
            get {
                object obj = ResourceManager.GetObject("walking e0003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_e0004 {
            get {
                object obj = ResourceManager.GetObject("walking e0004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_e0005 {
            get {
                object obj = ResourceManager.GetObject("walking e0005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_e0006 {
            get {
                object obj = ResourceManager.GetObject("walking e0006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_e0007 {
            get {
                object obj = ResourceManager.GetObject("walking e0007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_n0000 {
            get {
                object obj = ResourceManager.GetObject("walking n0000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_n0001 {
            get {
                object obj = ResourceManager.GetObject("walking n0001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_n0002 {
            get {
                object obj = ResourceManager.GetObject("walking n0002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_n0003 {
            get {
                object obj = ResourceManager.GetObject("walking n0003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_n0004 {
            get {
                object obj = ResourceManager.GetObject("walking n0004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_n0005 {
            get {
                object obj = ResourceManager.GetObject("walking n0005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_n0006 {
            get {
                object obj = ResourceManager.GetObject("walking n0006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_n0007 {
            get {
                object obj = ResourceManager.GetObject("walking n0007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_s0000 {
            get {
                object obj = ResourceManager.GetObject("walking s0000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_s0001 {
            get {
                object obj = ResourceManager.GetObject("walking s0001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_s0002 {
            get {
                object obj = ResourceManager.GetObject("walking s0002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_s0003 {
            get {
                object obj = ResourceManager.GetObject("walking s0003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_s0004 {
            get {
                object obj = ResourceManager.GetObject("walking s0004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_s0005 {
            get {
                object obj = ResourceManager.GetObject("walking s0005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_s0006 {
            get {
                object obj = ResourceManager.GetObject("walking s0006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_s0007 {
            get {
                object obj = ResourceManager.GetObject("walking s0007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_w0000 {
            get {
                object obj = ResourceManager.GetObject("walking w0000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_w0001 {
            get {
                object obj = ResourceManager.GetObject("walking w0001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_w0002 {
            get {
                object obj = ResourceManager.GetObject("walking w0002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_w0003 {
            get {
                object obj = ResourceManager.GetObject("walking w0003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_w0004 {
            get {
                object obj = ResourceManager.GetObject("walking w0004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_w0005 {
            get {
                object obj = ResourceManager.GetObject("walking w0005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_w0006 {
            get {
                object obj = ResourceManager.GetObject("walking w0006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap walking_w0007 {
            get {
                object obj = ResourceManager.GetObject("walking w0007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
